# --- Site Settings ---
title: Trọng Hiếu
slogan: tronghieuit.com
description: I am a web developer focusing on front-end development. Always hungry to keep learning.

read_speed: 300 # words per minute
excerpt_len: 100 # length of expert post

# social recommend 5 items
social:
  # url
  profile: https://tronghieuit.com/profile/
  # username
  facebook: tronghieu60s
  instagram:
  linkedin: tronghieu60s
  github: tronghieu60s
  #email address
  email: tronghieu60s@gmail.com

# --- Jekyll Settings ---

# jekyll permalinks
# more: https://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:slug/

# jekyll plugins
# more: https://jekyllrb.com/docs/plugins/
plugins: [jekyll-paginate]

# jekyll-paginate
# more: https://jekyllrb.com/docs/pagination/
paginate: 6
paginate_path: "/page/:num"
